version = 0.1

[default.deploy.parameters]
resolve_s3 = true
s3_prefix = "alert-broadcaster"
region = "ap-northeast-2"
capabilities = "CAPABILITY_IAM"

[rnd.deploy.parameters]
stack_name = "alert-broadcaster-rnd"
parameter_overrides = "StageName=rnd"

[dev.deploy.parameters]
stack_name = "alert-broadcaster-dev"
parameter_overrides = "StageName=dev"

[stg.deploy.parameters]
stack_name = "alert-broadcaster-stg"
parameter_overrides = "StageName=stg"

[prd.deploy.parameters]
stack_name = "alert-broadcaster-prd"
parameter_overrides = "StageName=prd"
